version: '3'
services:
  umbrella:
    build: .
    env_file: .env
    ports:
      - "9000:9000"
    networks:
      - frontend
      - backend
  redis:
    image: redis:latest
    networks:
      - backend
networks:
  backend:
  frontend:
